CREATE DATABASE customer_behavior;
USE customer_behavior;
SELECT * FROM customers LIMIT 20;
-- 1. What is the total revenue generated by male vs female customers?

SELECT gender, SUM(purchase_amount) as revenue
FROM customers
GROUP BY gender;  


-- 2. Which customer used a discount but still spent more than the average purchase amount?

SELECT customer_id, purchase_amount
FROM customers
WHERE discount_applied='Yes' AND purchase_amount>=(SELECT AVG(purchase_amount) FROM customers);


-- 3. Which are the top 5 products with the highest average review rating?

SELECT item_purchased, ROUND(AVG(review_rating),2) AS average_product_rating
FROM customers
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;


-- 4. Compare the average purchase amounts between Standard and Express Shipping.

SELECT shipping_type, ROUND(AVG(purchase_amount),2)
FROM customers
WHERE shipping_type in ('Standard','Express')
GROUP BY shipping_type ;


-- 5. Do subscribed customers spend more? Compare average spend and total rvenue between subscribers and non_subscribers.

SELECT subscription_status, 
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount),2) AS average_spend,
       ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customers
GROUP BY subscription_status
ORDER BY total_revenue, average_spend DESC;

-- 6. Which 5 products have the highest discount rate(percentage of times a discount was applied to the product out of total times it was purchased)?

SELECT item_purchased,
       ROUND(100*SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*), 2) AS discount_rate
FROM customers
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5; 


-- 7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.

WITH customer_type AS (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN "New"
    WHEN previous_purchases BETWEEN 2 AND 10 THEN "Returning"
    ELSE "Loyal"
    END as customer_segment
FROM customers
)

SELECT customer_segment, COUNT(*) AS 'Number of Customers'
FROM customer_type
GROUP BY customer_segment;

-- 8. What are the top 3 most purchased products within each category?

WITH ProductPurchases AS (
    SELECT
        category,
        item_purchased,
        COUNT(*) AS purchase_count
    FROM customers
    GROUP BY category, item_purchased
),
RankedProducts AS (
    SELECT
        category,
        item_purchased,
        purchase_count,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY purchase_count DESC
        ) AS rank_num
    FROM ProductPurchases
)
SELECT
    category,
    item_purchased,
    purchase_count
FROM RankedProducts
WHERE rank_num <= 3
ORDER BY category, purchase_count DESC;
 
 
-- 9. Are customers who are repeat buyers(more than 5 previous purchases) also likely to subscribe?

SELECT subscription_status, COUNT(customer_id) AS repeat_buyers
FROM customers
WHERE previous_purchases > 5
GROUP BY subscription_status; 


-- 10. What is the revenue contribution of each age group?

SELECT age_group, SUM(purchase_amount) AS total_revenue
FROM customers
GROUP BY age_group
ORDER BY total_revenue DESC;
    
       

       

 
